name: The World RCraft CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install
        run: |
          yarn install
      - name: yarn lint
        run: |
          yarn lint
      - name: yarn package-all
        run: |
          yarn package-all
      - uses: actions/upload-artifact@v1
        if: matrix.os == 'macos-latest'
        with:
          name: MacOs Release
          path: release/TheWorldRCraftLauncher-mac-setup.dmg

      - uses: actions/upload-artifact@v1
        if: matrix.os == 'windows-latest'
        with:
          name: Windows Release
          path: release/TheWorldRCraftLauncher-win-setup.exe

      - uses: actions/upload-artifact@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          name: Linux Release
          path: release/TheWorldRCraftLauncher-linux-setup.AppImage
